---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

# Relatório Mensal de vendas


```{r setup, include=FALSE}
library(flexdashboard)
```

```{r}
library(tidyverse)
library(readxl)
df <- read_excel("base-agregada.xlsx")
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
ggplot(df) +
  geom_point(aes(x = mass_co, y = mass_no))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
df %>% 
  gather(poluente, conc, mass_no, mass_co) %>% 
ggplot() +
  geom_line(aes(x = time, y = conc)) +
  facet_wrap(~poluente, scales = "free_y")
```

### Chart C

```{r}
p <- df %>% 
  gather(poluente, conc, mass_no, mass_co) %>% 
  group_by(poluente, hour) %>% 
  summarise(conc = mean(conc, na.rm = TRUE)) %>%
  ggplot() +
  geom_line(aes(x = hour, y = conc)) +
  facet_wrap(~poluente, scales = "free_y") +
  scale_x_continuous(breaks = seq(0, 24, 4))

plotly::ggplotly(p)
```



